# Generated by Django 5.0.7 on 2024-07-13 22:26

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="Короткое описание"),
                ),
                (
                    "long_description",
                    tinymce.models.HTMLField(
                        blank=True, verbose_name="Полное описание"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=14, max_digits=16, verbose_name="Долгота"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=14, max_digits=16, verbose_name="Широта"
                    ),
                ),
            ],
            options={
                "unique_together": {("longitude", "latitude")},
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, db_index=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imgs",
                        to="places.place",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
