# Generated by Django 4.1.13 on 2024-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="onmap_title",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
    ]
