# Generated by Django 5.0.7 on 2024-07-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_place_onmap_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="image",
            unique_together=set(),
        ),
    ]
