# Generated by Django 5.0.7 on 2024-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_image_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="coordinates",
            unique_together={("lng", "lat")},
        ),
    ]
